command:
  - /bin/bash
  - -c
  - ".venv/bin/python3 -m uvicorn app:app --host 0.0.0.0 --port 8000"
env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
resources:
  - name: sql-warehouse
    sql_warehouse:
      id: 557fdf4666f4883c
